import React, { createContext, useContext, ReactNode } from "react";
import { useQuery } from "@tanstack/react-query";
import type { Settings } from "@shared/schema";
import { format as formatDateFns, parseISO } from "date-fns";
import { toZonedTime } from "date-fns-tz";

interface SettingsContextType {
  settings: Settings | null;
  isLoading: boolean;
  formatDate: (date: Date | string, formatStr?: string) => string;
  formatDateTime: (date: Date | string) => string;
  t: (key: string) => string;
}

const SettingsContext = createContext<SettingsContextType | undefined>(undefined);

export function SettingsProvider({ children }: { children: ReactNode }) {
  const { data: settings, isLoading } = useQuery<Settings>({
    queryKey: ['/api/settings'],
    staleTime: 5 * 60 * 1000, // Cache for 5 minutes
  });

  // Format date according to user's preference
  const formatDate = (date: Date | string, customFormat?: string) => {
    if (!date) return "";
    
    const dateObj = typeof date === "string" ? parseISO(date) : date;
    const timezone = settings?.preferences.timezone || "UTC";
    const dateFormat = customFormat || settings?.preferences.dateFormat || "DD/MM/YYYY";
    
    // Convert to user's timezone
    const zonedDate = toZonedTime(dateObj, timezone);
    
    // Map our format strings to date-fns format strings
    const formatMap: Record<string, string> = {
      "DD/MM/YYYY": "dd/MM/yyyy",
      "MM/DD/YYYY": "MM/dd/yyyy",
      "YYYY-MM-DD": "yyyy-MM-dd",
    };
    
    const fnsFormat = formatMap[dateFormat] || "dd/MM/yyyy";
    return formatDateFns(zonedDate, fnsFormat);
  };

  // Format date and time according to user's preference
  const formatDateTime = (date: Date | string) => {
    if (!date) return "";
    
    const dateObj = typeof date === "string" ? parseISO(date) : date;
    const timezone = settings?.preferences.timezone || "UTC";
    const dateFormat = settings?.preferences.dateFormat || "DD/MM/YYYY";
    
    const zonedDate = toZonedTime(dateObj, timezone);
    
    const formatMap: Record<string, string> = {
      "DD/MM/YYYY": "dd/MM/yyyy HH:mm",
      "MM/DD/YYYY": "MM/dd/yyyy hh:mm a",
      "YYYY-MM-DD": "yyyy-MM-dd HH:mm",
    };
    
    const fnsFormat = formatMap[dateFormat] || "dd/MM/yyyy HH:mm";
    return formatDateFns(zonedDate, fnsFormat);
  };

  // Basic translation function (can be expanded with actual i18n library)
  const t = (key: string): string => {
    const language = settings?.preferences.language || "en";
    
    // Translation dictionary
    const translations: Record<string, Record<string, string>> = {
      en: {
        dashboard: "Dashboard",
        customers: "Customers",
        reminders: "Reminders",
        reports: "Reports & Analytics",
        admins: "Admin Management",
        settings: "Settings",
        profile: "Profile",
        logout: "Logout",
        welcome: "Welcome",
        "open_cases": "Open Cases",
        "pending_cases": "Pending Cases",
        "closed_cases": "Closed Cases",
        "total_customers": "Total Customers",
        "case_id": "Case ID",
        status: "Status",
        "created_at": "Created",
        store: "Store",
        actions: "Actions",
        "export_excel": "Export to Excel",
        "export_pdf": "Export to PDF",
        "no_data": "No data available",
        "create_case": "Create Case",
        "quick_case": "Quick Case",
        "all_cases": "All Cases",
        "by_store": "by Store",
        "missing_info": "Missing Information",
        "expand": "Expand",
        "collapse": "Collapse",
        "click_to": "Click to",
        "add_customer": "Add Customer",
        "phone_number": "Phone Number",
        "email_address": "Email Address",
        "address": "Address",
        "cancel": "Cancel",
        "save": "Save",
        "create": "Create",
        "edit": "Edit",
        "delete": "Delete",
        "search": "Search",
        "export": "Export",
        "import": "Import",
        "filter": "Filter",
        "all": "All",
        "new": "New",
        "pending": "Pending",
        "completed": "Completed",
        "in_progress": "In Progress",
        "cancelled": "Cancelled",
        "high": "High",
        "medium": "Medium",
        "low": "Low",
        "urgent": "Urgent",
        priority: "Priority",
        "title": "Title",
        "description": "Description",
        "due_date": "Due Date",
        "created": "Created",
        "updated": "Updated",
        "assigned_by": "Assigned By",
        "assigned_to": "Assigned To",
        "no_results": "No results found",
        "search_placeholder": "Search...",
        "select_customer": "Select Customer",
        "create_new_case": "Create New Case",
        "case_details": "Case Details",
        "customer_info": "Customer Information",
        "customer_name": "Customer Name",
        "serial_number": "Serial Number",
        "model_number": "Model Number",
        "purchase_place": "Purchase Place",
        "receipt_number": "Receipt Number",
        "date_of_purchase": "Date of Purchase",
        "repair_needed": "Repair Needed",
        "initial_summary": "Initial Summary",
        "case_status": "Case Status",
        "payment_status": "Payment Status",
        "shipping_cost": "Shipping Cost",
        "save_changes": "Save Changes",
        "creating": "Creating...",
        "saving": "Saving...",
        "sign_in": "Sign In",
        "signing_in": "Signing in...",
        "username": "Username",
        "password": "Password",
        "enter_username": "Enter your username",
        "enter_password": "Enter your password",
        "customer_case_management": "Customer Case Management",
        "sign_in_access": "Sign in to access the admin dashboard",
        "profile_info": "Profile Information",
        "update_personal_info": "Update your personal information and credentials",
        "full_name": "Full Name",
        "avatar_url": "Avatar URL (optional)",
        "new_password": "New Password (optional)",
        "confirm_password": "Confirm New Password",
        "leave_blank": "Leave blank to keep current",
        "min_6_chars": "Min 6 characters",
        "must_match": "Must match new password",
        "password_change_note": "Leave password fields blank if you don't want to change your password. Only fill them if you want to set a new password.",
        "page_not_found": "Page Not Found",
        "page_not_exist": "The page you're looking for doesn't exist or has been moved.",
        "go_back": "Go Back",
        "go_home": "Go Home",
        "export_settings": "Export Settings",
        "configure_export": "Configure data export preferences",
        "default_export_format": "Default Export Format",
        "include_filters": "Include Current Filters",
        "apply_active_filters": "Apply active filters when exporting",
        "export_available": "Export Available For:",
        "cases_list": "Cases List",
        "customers_list": "Customers List",
        "reminders_list": "Reminders List",
        "reports_analytics": "Reports & Analytics",
        "language": "Language",
        "system_language": "System language (requires page reload)",
        "date_format": "Date Format",
        "date_display": "How dates are displayed throughout the system",
        "reset_defaults": "Reset to Defaults",
        "unsaved_changes": "Unsaved changes",
        "team_reminders": "Team Reminders",
        "new_reminder": "New Reminder",
        "create_team_reminder": "Create Team Reminder",
        "assign_task": "Assign a task or reminder to team members",
        "provide_details": "Provide details...",
        "optional": "Optional",
        "assign_to": "Assign To",
        "all_members": "All Members",
        "no_subadmins": "No subadmins available",
        "members_selected": "members selected",
        "create_reminder": "Create Reminder",
        "no_reminders": "No Reminders Found",
        "create_reminder_start": "Create a reminder to get started",
        "no_reminders_assigned": "You have no reminders assigned",
        "delete_reminder": "Delete Reminder",
        "delete_confirmation": "Are you sure you want to delete this reminder? This action cannot be undone.",
        "update_status": "Update Status",
        "mark_pending": "Mark as Pending",
        "mark_progress": "Mark In Progress",
        "mark_completed": "Mark Completed",
        "mark_cancelled": "Cancel",
        "overdue": "OVERDUE",
        "from": "From",
        "to": "To",
        "due": "Due",
      },
      "en-US": {
        dashboard: "Dashboard",
        customers: "Customers",
        reminders: "Reminders",
        reports: "Reports & Analytics",
        admins: "Admin Management",
        settings: "Settings",
        profile: "Profile",
        logout: "Logout",
        welcome: "Welcome",
        "open_cases": "Open Cases",
        "pending_cases": "Pending Cases",
        "closed_cases": "Closed Cases",
        "total_customers": "Total Customers",
        "case_id": "Case ID",
        status: "Status",
        "created_at": "Created",
        store: "Store",
        actions: "Actions",
        "export_excel": "Export to Excel",
        "export_pdf": "Export to PDF",
        "no_data": "No data available",
        loading: "Loading...",
      },
      "en-GB": {
        dashboard: "Dashboard",
        customers: "Customers",
        reminders: "Reminders",
        reports: "Reports & Analytics",
        admins: "Admin Management",
        settings: "Settings",
        profile: "Profile",
        logout: "Logout",
        welcome: "Welcome",
        "open_cases": "Open Cases",
        "pending_cases": "Pending Cases",
        "closed_cases": "Closed Cases",
        "total_customers": "Total Customers",
        "case_id": "Case ID",
        status: "Status",
        "created_at": "Created",
        store: "Store",
        actions: "Actions",
        "export_excel": "Export to Excel",
        "export_pdf": "Export to PDF",
        "no_data": "No data available",
        loading: "Loading...",
      },
      ar: {
        dashboard: "لوحة القيادة",
        customers: "العملاء",
        reminders: "التذكيرات",
        reports: "التقارير والتحليلات",
        admins: "إدارة المسؤولين",
        settings: "الإعدادات",
        profile: "الملف الشخصي",
        logout: "تسجيل الخروج",
        welcome: "مرحبا",
        "open_cases": "الحالات المفتوحة",
        "pending_cases": "الحالات المعلقة",
        "closed_cases": "الحالات المغلقة",
        "total_customers": "إجمالي العملاء",
        "case_id": "رقم الحالة",
        "customer_name": "اسم العميل",
        status: "الحالة",
        "assigned_to": "مسند إلى",
        "created_at": "تاريخ الإنشاء",
        priority: "الأولوية",
        store: "المتجر",
        actions: "الإجراءات",
        "export_excel": "تصدير إلى Excel",
        "export_pdf": "تصدير إلى PDF",
        "no_data": "لا توجد بيانات",
        loading: "جار التحميل...",
      },
      fr: {
        dashboard: "Tableau de bord",
        customers: "Clients",
        reminders: "Rappels",
        reports: "Rapports et analyses",
        admins: "Gestion des administrateurs",
        settings: "Paramètres",
        profile: "Profil",
        logout: "Déconnexion",
        welcome: "Bienvenue",
        "open_cases": "Cas ouverts",
        "pending_cases": "Cas en attente",
        "closed_cases": "Cas fermés",
        "total_customers": "Total des clients",
        "case_id": "ID du cas",
        "customer_name": "Nom du client",
        status: "Statut",
        "assigned_to": "Assigné à",
        "created_at": "Créé le",
        priority: "Priorité",
        store: "Magasin",
        actions: "Actions",
        "export_excel": "Exporter vers Excel",
        "export_pdf": "Exporter vers PDF",
        "no_data": "Aucune donnée disponible",
        loading: "Chargement...",
      },
      he: {
        dashboard: "לוח בקרה",
        customers: "לקוחות",
        reminders: "תזכורות",
        reports: "דוחות וניתוחים",
        admins: "ניהול מנהלים",
        settings: "הגדרות",
        profile: "פרופיל",
        logout: "התנתק",
        welcome: "ברוך הבא",
        "open_cases": "תיקים פתוחים",
        "pending_cases": "תיקים ממתינים",
        "closed_cases": "תיקים סגורים",
        "total_customers": "סך הלקוחות",
        "case_id": "מזהה תיק",
        "customer_name": "שם הלקוח",
        status: "סטטוס",
        "assigned_to": "מוקצה ל",
        "created_at": "נוצר",
        priority: "עדיפות",
        store: "חנות",
        actions: "פעולות",
        "export_excel": "ייצא ל-Excel",
        "export_pdf": "ייצא ל-PDF",
        "no_data": "אין נתונים זמינים",
        loading: "טוען...",
      },
      es: {
        dashboard: "Panel de control",
        customers: "Clientes",
        reminders: "Recordatorios",
        reports: "Informes y análisis",
        admins: "Gestión de administradores",
        settings: "Configuración",
        profile: "Perfil",
        logout: "Cerrar sesión",
        welcome: "Bienvenido",
        "open_cases": "Casos abiertos",
        "pending_cases": "Casos pendientes",
        "closed_cases": "Casos cerrados",
        "total_customers": "Total de clientes",
        "case_id": "ID del caso",
        "customer_name": "Nombre del cliente",
        status: "Estado",
        "assigned_to": "Asignado a",
        "created_at": "Creado",
        priority: "Prioridad",
        store: "Tienda",
        actions: "Acciones",
        "export_excel": "Exportar a Excel",
        "export_pdf": "Exportar a PDF",
        "no_data": "No hay datos disponibles",
        loading: "Cargando...",
      },
      de: {
        dashboard: "Dashboard",
        customers: "Kunden",
        reminders: "Erinnerungen",
        reports: "Berichte & Analysen",
        admins: "Admin-Verwaltung",
        settings: "Einstellungen",
        profile: "Profil",
        logout: "Abmelden",
        welcome: "Willkommen",
        "open_cases": "Offene Fälle",
        "pending_cases": "Ausstehende Fälle",
        "closed_cases": "Geschlossene Fälle",
        "total_customers": "Gesamtkunden",
        "case_id": "Fall-ID",
        "customer_name": "Kundenname",
        status: "Status",
        "assigned_to": "Zugewiesen an",
        "created_at": "Erstellt",
        priority: "Priorität",
        store: "Geschäft",
        actions: "Aktionen",
        "export_excel": "Nach Excel exportieren",
        "export_pdf": "Nach PDF exportieren",
        "no_data": "Keine Daten verfügbar",
        loading: "Laden...",
      },
      it: {
        dashboard: "Dashboard",
        customers: "Clienti",
        reminders: "Promemoria",
        reports: "Report e analisi",
        admins: "Gestione amministratori",
        settings: "Impostazioni",
        profile: "Profilo",
        logout: "Disconnetti",
        welcome: "Benvenuto",
        "open_cases": "Casi aperti",
        "pending_cases": "Casi in sospeso",
        "closed_cases": "Casi chiusi",
        "total_customers": "Clienti totali",
        "case_id": "ID caso",
        "customer_name": "Nome cliente",
        status: "Stato",
        "assigned_to": "Assegnato a",
        "created_at": "Creato",
        priority: "Priorità",
        store: "Negozio",
        actions: "Azioni",
        "export_excel": "Esporta in Excel",
        "export_pdf": "Esporta in PDF",
        "no_data": "Nessun dato disponibile",
        loading: "Caricamento...",
      },
      pt: {
        dashboard: "Painel",
        customers: "Clientes",
        reminders: "Lembretes",
        reports: "Relatórios e análises",
        admins: "Gestão de administradores",
        settings: "Configurações",
        profile: "Perfil",
        logout: "Sair",
        welcome: "Bem-vindo",
        "open_cases": "Casos abertos",
        "pending_cases": "Casos pendentes",
        "closed_cases": "Casos fechados",
        "total_customers": "Total de clientes",
        "case_id": "ID do caso",
        "customer_name": "Nome do cliente",
        status: "Status",
        "assigned_to": "Atribuído a",
        "created_at": "Criado",
        priority: "Prioridade",
        store: "Loja",
        actions: "Ações",
        "export_excel": "Exportar para Excel",
        "export_pdf": "Exportar para PDF",
        "no_data": "Nenhum dado disponível",
        loading: "Carregando...",
      },
      zh: {
        dashboard: "仪表板",
        customers: "客户",
        reminders: "提醒",
        reports: "报告与分析",
        admins: "管理员管理",
        settings: "设置",
        profile: "个人资料",
        logout: "登出",
        welcome: "欢迎",
        "open_cases": "开放案例",
        "pending_cases": "待处理案例",
        "closed_cases": "已关闭案例",
        "total_customers": "客户总数",
        "case_id": "案例ID",
        "customer_name": "客户姓名",
        status: "状态",
        "assigned_to": "分配给",
        "created_at": "创建时间",
        priority: "优先级",
        store: "商店",
        actions: "操作",
        "export_excel": "导出到Excel",
        "export_pdf": "导出到PDF",
        "no_data": "无可用数据",
        loading: "加载中...",
      },
      ja: {
        dashboard: "ダッシュボード",
        customers: "顧客",
        reminders: "リマインダー",
        reports: "レポートと分析",
        admins: "管理者管理",
        settings: "設定",
        profile: "プロフィール",
        logout: "ログアウト",
        welcome: "ようこそ",
        "open_cases": "オープンケース",
        "pending_cases": "保留中のケース",
        "closed_cases": "クローズドケース",
        "total_customers": "総顧客数",
        "case_id": "ケースID",
        "customer_name": "顧客名",
        status: "ステータス",
        "assigned_to": "担当者",
        "created_at": "作成日",
        priority: "優先度",
        store: "店舗",
        actions: "アクション",
        "export_excel": "Excelにエクスポート",
        "export_pdf": "PDFにエクスポート",
        "no_data": "利用可能なデータがありません",
        loading: "読み込み中...",
      },
      hi: {
        dashboard: "डैशबोर्ड",
        customers: "ग्राहक",
        reminders: "अनुस्मारक",
        reports: "रिपोर्ट और विश्लेषण",
        admins: "व्यवस्थापक प्रबंधन",
        settings: "सेटिंग्स",
        profile: "प्रोफ़ाइल",
        logout: "लॉग आउट",
        welcome: "स्वागत है",
        "open_cases": "खुले मामले",
        "pending_cases": "लंबित मामले",
        "closed_cases": "बंद मामले",
        "total_customers": "कुल ग्राहक",
        "case_id": "केस आईडी",
        "customer_name": "ग्राहक का नाम",
        status: "स्थिति",
        "assigned_to": "को सौंपा गया",
        "created_at": "बनाया गया",
        priority: "प्राथमिकता",
        store: "स्टोर",
        actions: "क्रियाएँ",
        "export_excel": "Excel में निर्यात करें",
        "export_pdf": "PDF में निर्यात करें",
        "no_data": "कोई डेटा उपलब्ध नहीं",
        loading: "लोड हो रहा है...",
      },
    };
    
    return translations[language]?.[key] || key;
  };

  const value: SettingsContextType = {
    settings: settings || null,
    isLoading,
    formatDate,
    formatDateTime,
    t,
  };

  return (
    <SettingsContext.Provider value={value}>
      {children}
    </SettingsContext.Provider>
  );
}

export function useSettings() {
  const context = useContext(SettingsContext);
  if (context === undefined) {
    throw new Error("useSettings must be used within a SettingsProvider");
  }
  return context;
}
